---
title: "SIR Modelling Population Turnover"
output:
  word_document: default
  html_document: default
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
```

## LOAD THE PACKAGES:

```{r}
library(deSolve)
library(reshape2)
library(ggplot2)
```

## Model Inputs

```{r}
initial_state_values <- c(S = 1000000-1, I = 1, R = 0)           


parameters <- c(beta = 0.4*365, gamma = 0.2*365,     
                mu = 1/70, b = 1/70) 
```

## Timesteps
```{r}
times <- seq(from = 0, to = 400, by = 2/365)  
```

## SIR Modeling Function
```{r}
sir_model <- function(time, state, parameters) {  

    with(as.list(c(state, parameters)), {     
        
    
      N <- S+I+R
      
   
      lambda <- beta * I/N
        
  
      dS <- -lambda * S - mu * S + b * N            
      dI <- lambda * S - gamma * I  - mu * I           
      dR <- gamma * I - mu * R               
      
   
    return(list(c(dS, dI, dR))) 
    })
  
}
```

## Model Output
```{r}
output <- as.data.frame(ode(y = initial_state_values, 
                            times = times, func = sir_model,
                            parms = parameters))
```

## Plot
```{r}
ggplot(data = output,                                               
       aes(x = time, y = I)) +                                          
  geom_line() +                                                          
  xlab("Time (years)")+                                                  
  ylab("Number of infected people") +                                    
  labs(title = "Epidemic curve in the first year after introduction of an infected case") +    
  xlim(c(0,1))

```

## Plotting the long-term epidemic
```{r}
output_long <- melt(as.data.frame(output), id = "time")                 


ggplot(data = output, aes(x = time, y = I)) +                                          
  geom_line() +                                                      
  xlab("Time (years)")+                                               
  ylab("Number of infected people") +                                
  labs(title = "Epidemic curve over 4 generations") 
```

## What do you observe about the long-term disease dynamics under these assumptions
```{r}
output_long <- melt(as.data.frame(output), id = "time")                


output_long$proportion <- output_long$value/sum(initial_state_values)


ggplot(data = output_long,                                               
       aes(x = time, y = proportion, colour = variable, group = variable)) +  
  geom_line() +                                                          
  xlab("Time (years)")+                                                  
  ylab("Prevalence (proportion)") +                                      
  labs(colour = "Compartment",                                            
       title = "Prevalence of susceptible, infected and recovered people over time")
```

## Modelling this population over 1 year:

```{r}
# MODEL INPUTS:


initial_state_values <- c(S = 1000000-1,  I = 1, R = 0)          


parameters <- c(beta = 0.4, gamma = 0.2,  mu = 1/28,      
                b = 1/28)       
```
## TIMESTEPS:
```{r}
times <- seq(from = 0, to = 365, by = 1)   
```
## SIR MODEL FUNCTION: 

```{r}
sir_model <- function(time, state, parameters) {  

    with(as.list(c(state, parameters)), {    
        
    
      N <- S+I+R
      
    
      lambda <- beta * I/N
        
   
      dS <- -lambda * S - mu * S + b * N            
      dI <- lambda * S - gamma * I  - mu * I           
      dR <- gamma * I - mu * R               
      
   
    return(list(c(dS, dI, dR))) 
    })
  
}
```
## MODEL OUTPUT:
```{r}
output_pigs <- as.data.frame(ode(y = initial_state_values, 
                            times = times, 
                            func = sir_model,
                            parms = parameters))
```
# PLOT
```{r}
output_pigs_long <- melt(as.data.frame(output_pigs), id = "time")        


output_pigs_long$prevalence <- output_pigs_long$value/sum(initial_state_values)


ggplot(data = output_pigs_long,                                               
       aes(x = time, y = prevalence, colour = variable, group = variable)) +  
  geom_line() +                                                         
  xlab("Time (days)")+                                                  
  ylab("Prevalence (proportion)") +                                      
  labs(colour = "Compartment",                                          
       title = "Prevalence of infection, susceptibility and recovery over time") +  
  theme(legend.position = "bottom")
```
## Effective reproduction number over time
```{r}

output_pigs$reff <- parameters["beta"]/parameters["gamma"] *                    
                      output_pigs$S/(output_pigs$S+output_pigs$I+output_pigs$R) 
                                                                                

# Plot Reff
ggplot(data = output_pigs,                                              
       aes(x = time, y = reff)) +                                         
  geom_line() +                                                          
  xlab("Time (days)")+                                                   
  ylab("Reff") +                                                         
  labs(title = "Effective reproduction number over time") +              
  ylim(c(0,2))
```

